In [ ]:
!pip install --quiet requests pandas python-dotenv SQLAlchemy psycopg2-binary

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 24.6 MB/s eta 0:00:00

In [ ]:
import os
from datetime import datetime, timezone

In [ ]:
#list of coingecko ids and symbols we will use
COINS =[{"id":"bitcoin","symbol":"BTC"},
        {"id":"ethereum","symbol":"ETH"},
        {"id":"solana", "symbol":"SOL"}]

#quote currency price
VS_CURRENCY = "usd"

#how many days of history to fetch from coingecko
HISTORY_DAYS = 365

In [ ]:
#defining Postgre URI connection string from Neon Database
POSTGRES_URI ='postgresql+psycopg2://neondb_owner:npg_yVQ1kzD0INun@ep-nameless-fog-aob2dfqo-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'

In [ ]:
#COIN GECKO HELPER FUNCTIONS

#import pandas and requests
import requests
import pandas as pd

In [ ]:
#defining coin gecko base url
COINGECKO_BASE_URL = "https://api.coingecko.com/api/v3"

In [ ]:
#defining function to fetch market chart from coin gecko
def fetch_market_chart(coin_id:str, vs_currency: str, days:int)->dict:
    """
    Call CoinGecko /market_chart endpoint and return raw JSON.
    Docs: /coins/{id}/market_chart[web:514]
    """
    url =f"{COINGECKO_BASE_URL}/coins/{coin_id}/market_chart"
    params={"vs_currency" : vs_currency,
            "days" : days,
            "interval": "daily"} #daily candlesticks
    resp=requests.get(url,params=params,timeout = 30)
    resp.raise_for_status() #raise errors if api call fail
    return resp.json()

In [ ]:
#defining function for market chart to dataframe

def market_chart_to_df(raw : dict, coin_id : str, symbol : str, vs_currency: str)->pd.DataFrame:
    """
    Convert CoinGecko market_chart response into a tidy time-series DataFrame.
    We align prices, market caps, and volumes on the same datetime index.
    """
    #Each list is [timestamp_ms,value]
    prices = pd.DataFrame(raw["prices"], columns=["timestamp_ms","price"])
    market_caps = pd.DataFrame(raw["market_caps"], columns=["timestamp_ms","market_cap"])
    volumes = pd.DataFrame(raw["total_volumes"], columns=["timestamp_ms","volume"])

    #Merging the three dataframes on the column "timestamp_ms"
    df= prices.merge(market_caps, on="timestamp_ms").merge(volumes,on = "timestamp_ms")
    #Converting timestamp ms to datetime and setting it as index
    df["timestamp"] = pd.to_datetime(df["timestamp_ms"], unit ="ms", utc =True)
    df= df.drop(columns=["timestamp_ms"]).set_index("timestamp").sort_index()

    #Adding identifiers
    df["coin_id"] = coin_id
    df["symbol"] = symbol
    df["vs_currency"] = vs_currency

    #Ensuring proper column sequence in the dataframe
    df=df[["coin_id", "symbol", "vs_currency", "price", "market_cap", "volume"]]

    return df

In [ ]:
#FETCHING DATA FOR ALL CONFIGURED COINS

all_dfs =[]

for c in COINS:
    coin_id = c["id"]
    symbol = c["symbol"]
    print(f"Fetching {HISTORY_DAYS} days for {symbol} ({coin_id})....")
    raw = fetch_market_chart(coin_id, VS_CURRENCY, HISTORY_DAYS)
    df_coin = market_chart_to_df(raw, coin_id, symbol, VS_CURRENCY)
    all_dfs.append(df_coin)

#Concatenating into a single multi-coin dataframe
prices_df = pd.concat(all_dfs).sort_index()

#Displaying the end of the dataframe
prices_df.tail()

Fetching 365 days for BTC (bitcoin)....
Fetching 365 days for ETH (ethereum)....
Fetching 365 days for SOL (solana)....

,coin_id,symbol,vs_currency,price,market_cap,volume
timestamp,,,,,,
2026-05-18 00:00:00+00:00,bitcoin,BTC,usd,77425.715192,1.547173e+12,2.298513e+10
2026-05-18 00:00:00+00:00,ethereum,ETH,usd,2128.000228,2.568194e+11,9.287605e+09
2026-05-18 07:46:15+00:00,bitcoin,BTC,usd,76940.109007,1.541162e+12,2.858899e+10
2026-05-18 07:46:38+00:00,solana,SOL,usd,84.556656,4.897294e+10,2.644279e+09
2026-05-18 07:46:43+00:00,ethereum,ETH,usd,2116.197711,2.553688e+11,1.293639e+10

In [ ]:
#CALCULATING METRICS PER COIN
#importing numpy as np
import numpy as np

#Defining function for computinng coin metrics
def compute_metrics(df : pd.DataFrame, window_vol:int = 30) ->pd.DataFrame:
    """
    Compute returns, volatility, moving averages, and drawdown metrics.
    Operates per-coin, so we will groupby symbol/coin_id.
    """
    #copying the dataframe into a newly created dataframe
    df = df.copy()
    #sorting the dataframe by time for convenience
    df = df.sort_index()

    #calculating simple daily returns percentage
    df["return"] = df["price"].pct_change().astype(float)

    #calculating log returns which are better compounding math and volatility
    df["log_return"] = np.log(df["price"] / df["price"].shift(1))     #apply(lambda x: pd.NA if pd.isna(x) else np.log(x))
    df["log_return"] = df["log_return"].replace([np.inf, -np.inf], np.nan).astype(float)

    # Rolling volatility of daily returns over 'window_vol' days, annualized
    # sigma_annual = std(returns) * sqrt(365)
    rolling_std = df["return"].rolling(window_vol).std()
    df["volatility_annual_pct"] = rolling_std * (365**0.5) * 100

    #calculating moving average for trend analysis
    df["ma_50"] = df["price"].rolling(50).mean()
    df["ma_200"] = df["price"].rolling(200).mean()

    #Drawdown Calculations
    #1. Wealth Curve from cumulative returns
    df["wealth"] = (1 + df["return"].fillna(0)).cumprod()
    #2. Running peak of wealth using expanding().max()
    df["wealth_peak"] = df["wealth"].expanding().max()
    #3. Drawdown is how far wealth is below the peak(negative = loss)
    df["drawdown_pct"] = (df["wealth"] / df["wealth_peak"] - 1) * 100

    return df

#applying metrics per using groupby function
metrics_df = (prices_df.groupby(["coin_id", "symbol", "vs_currency"], group_keys = False).apply(compute_metrics))

#displaying the end of the metrics dataframe
metrics_df.tail()

/tmp/ipykernel_6010/1374017669.py:43: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  metrics_df = (prices_df.groupby(["coin_id", "symbol", "vs_currency"], group_keys = False).apply(compute_metrics))

,coin_id,symbol,vs_currency,price,market_cap,volume,return,log_return,volatility_annual_pct,ma_50,ma_200,wealth,wealth_peak,drawdown_pct
timestamp,,,,,,,,,,,,,,
2026-05-18 00:00:00+00:00,ethereum,ETH,usd,2128.000228,2.568194e+11,9.287605e+09,-0.023798,-0.024086,33.688266,2257.024450,2601.596541,0.863167,1.958847,-55.934959
2026-05-18 00:00:00+00:00,solana,SOL,usd,85.158905,4.916614e+10,2.156422e+09,-0.015665,-0.015789,40.244123,85.828193,110.280450,0.496436,1.443134,-65.600181
2026-05-18 07:46:15+00:00,bitcoin,BTC,usd,76940.109007,1.541162e+12,2.858899e+10,-0.006272,-0.006292,28.485442,75638.104817,81432.259554,0.725640,1.176768,-38.336182
2026-05-18 07:46:38+00:00,solana,SOL,usd,84.556656,4.897294e+10,2.644279e+09,-0.007072,-0.007097,38.961260,85.892536,109.781801,0.492925,1.443134,-65.843459
2026-05-18 07:46:43+00:00,ethereum,ETH,usd,2116.197711,2.553688e+11,1.293639e+10,-0.005546,-0.005562,32.487239,2259.684721,2593.166053,0.858379,1.958847,-56.179356

In [ ]:
#BUILDING A LATEST SNAPSHOT TABLE PER COIN
#USEFUL FOR USING SUPERSET DASHBOARDS

#taking the latest available row for eacch coin
latest_snapshot = (metrics_df.groupby(["coin_id", "symbol", "vs_currency"]).tail(1).reset_index())

#keeping only relevant summary columns
snapshot_cols = ["coin_id",
                 "symbol",
                 "vs_currency",
                 "timestamp",
                 "price",
                 "market_cap",
                 "volume",
                 "return",                     #last daily return
                 "volatility_annual_pct",
                 "ma_50",
                 "ma_200",
                 "drawdown_pct"]

#creating snapshot dataframe
snapshot_df = latest_snapshot[["timestamp"] + [c for c in snapshot_cols if c!= "timestamp"]]

#displaying the snapshot dataframe
snapshot_df

,timestamp,coin_id,symbol,vs_currency,price,market_cap,volume,return,volatility_annual_pct,ma_50,ma_200,drawdown_pct
0,2026-05-18 07:46:15+00:00,bitcoin,BTC,usd,76940.109007,1.541162e+12,2.858899e+10,-0.006272,28.485442,75638.104817,81432.259554,-38.336182
1,2026-05-18 07:46:38+00:00,solana,SOL,usd,84.556656,4.897294e+10,2.644279e+09,-0.007072,38.961260,85.892536,109.781801,-65.843459
2,2026-05-18 07:46:43+00:00,ethereum,ETH,usd,2116.197711,2.553688e+11,1.293639e+10,-0.005546,32.487239,2259.684721,2593.166053,-56.179356

In [ ]:
# Cleaning data types and writing tables to Neon Database

from sqlalchemy import create_engine, types as sqltypes

# 1) Start from metrics_df, ensure index is sorted and timezone-naive
metrics_clean = metrics_df.sort_index().copy()

# If your index is UTC, drop the timezone info for Postgres compatibility
if metrics_clean.index.tz is not None:
    metrics_clean.index = metrics_clean.index.tz_convert(None)

# Turn index into a normal column called "timestamp"
metrics_out = metrics_clean.reset_index().rename(columns={"index": "timestamp"})

# Make sure timestamp is a plain datetime64[ns]
metrics_out["timestamp"] = pd.to_datetime(metrics_out["timestamp"])

# 2) Force numeric columns to float
metric_numeric_cols = [
    "price",
    "market_cap",
    "volume",
    "return",
    "log_return",
    "volatility_annual_pct",
    "ma_50",
    "ma_200",
    "wealth",
    "wealth_peak",
    "drawdown_pct",
]

for col in metric_numeric_cols:
    metrics_out[col] = pd.to_numeric(metrics_out[col], errors="coerce")

# 3) Clean snapshot_df as well
snapshot_out = snapshot_df.copy()

# If snapshot timestamp has timezone, drop it
if hasattr(snapshot_out["timestamp"], "dt") and snapshot_out["timestamp"].dt.tz is not None:
    snapshot_out["timestamp"] = snapshot_out["timestamp"].dt.tz_convert(None)

snapshot_out["timestamp"] = pd.to_datetime(snapshot_out["timestamp"])

snapshot_numeric_cols = [
    "price",
    "market_cap",
    "volume",
    "return",
    "volatility_annual_pct",
    "ma_50",
    "ma_200",
    "drawdown_pct",
]

for col in snapshot_numeric_cols:
    snapshot_out[col] = pd.to_numeric(snapshot_out[col], errors="coerce")

# 4) Create Neon engine
engine = create_engine(POSTGRES_URI)

# (Optional but good practice) – basic dtype mapping for key columns
metrics_dtypes = {
    "timestamp": sqltypes.DateTime(),   # becomes TIMESTAMP WITHOUT TIME ZONE
    "coin_id": sqltypes.String(64),
    "symbol": sqltypes.String(16),
    "vs_currency": sqltypes.String(16),
}

snapshot_dtypes = metrics_dtypes

# 5) Write full time-series table
metrics_out.to_sql(
    name="crypto_timeseries",
    con=engine,
    if_exists="replace",   # use 'append' later for incremental
    index=False,
    dtype=metrics_dtypes,
)

# 6) Write snapshot table
snapshot_out.to_sql(
    name="crypto_snapshot",
    con=engine,
    if_exists="replace",
    index=False,
    dtype=snapshot_dtypes,
)

print("Data written to Neon PostgreSQL.")

Data written to Neon PostgreSQL.